version: '3'

services:
      web:
        image: nginx
        container_name: nginx
        ports:
        - 80:80
        tty: true
        restart: unless-stopped
        volumes:
        - ./onie:/var/www/
        - ./nginx.conf:/etc/nginx/nginx.conf
